networks:
  watchtogether-network:
    driver: bridge


services:
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - watchtogether-network
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - watchtogether-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - watchtogether-network
      
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    networks:
      - watchtogether-network

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${APP_PORT:-80}:80"
    networks:
      - watchtogether-network

volumes:
  pg_data:
